.

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -28,7 +28,11 @@ init-base-settings() {
     autoload -U run-help
     autoload run-help-sudo
     autoload run-help-git
-    unalias run-help
+    autoload run-help-docker
+    if which run-help | grep aliased >/dev/null 2>&1; then
+        unalias run-help
+    fi
+
 
     # Vim for tty
     if [[ -n "$SSH_TTY" ]] ; then
@@ -43,7 +47,9 @@ init-base-settings() {
         # }
     fi
 
-    export LC_ALL='en_US.UTF-8'
+    # smokeping is complaining. Better to use LANG instead of LC_ALL
+    # https://www.google.ru/search?client=opera&q=Resetting+LC_NUMERIC+failed+probably+because+your+international+setup+of+the&sourceid=opera&ie=UTF-8&oe=UTF-8
+    # export LC_ALL='en_US.UTF-8'
 
     export ALTERNATE_EDITOR="vim"
     export SYSTEMD_EDITOR=$MAINEDITOR
@@ -97,7 +103,8 @@ init-oh-my-zsh() {
 
     plugins=(git fasd gitfast common-aliases wd safe-paste docker)
     if [ -f "/etc/arch-release" ]; then
-        plugins+=(archlinux)
+        # I do not want to hide pacupg binary with alias
+        # plugins+=(archlinux)
         export SSH_AUTH_SOCK=/run/user/1000/ssh-agent.socket
         # elif `which ssh-agent &>/dev/null`; then
         #     plugins+=(ssh-agent)
@@ -142,20 +149,27 @@ init-simple-aliases() {
     alias help='man'
     alias cal='cal -m'
     alias dmesgl='dmesg --color=always | less -R'
-    alias ll='ls -hlAt'
+    alias ll='ls -hlAt --group-directories-first'
     alias mp='mpv'
+    alias cdd='cd ~/Downloads'
     alias pia='ping ya.ru'
     alias pil='ping lislon.ru'
+    alias ytmp3='youtube-dl --extract-audio --audio-quality 0 --audio-format mp3 ' # works for playlists too
     alias bb='sudo /usr/bin/shutdown now'
     alias bbr='sudo /usr/bin/shutdown -r now'
-    alias bbh='systemctl suspend'
+    alias bbh='_emacs-clock-out && systemctl suspend'
+    alias emacsrestart='systemctl --user restart emacs-daemon'
+    alias emacsstop='systemctl --user stop emacs-daemon'
     alias svim='SUDO_EDITOR=vim sudoedit'
     alias cx='chmod +x'
-    alias feh='feh --scale-down'
+    alias feh='feh --scale-down \
+--action1 "readlink -f %F | xclip -selection clipboard -f | xclip -selection p" \
+--action2 "NAME=\$(zenity --entry) && echo cp %F \"\$(dirname %F)/$NAME\""'
     alias -s pdf='xdg-open'
     alias -s html='chromium'
     alias emax="emacsclient -nw"                      # used to be "emacs -nw"
     alias e="$EDITOR"
+    alias open="xdg-open"
     #alias semac="sudo emacsclient -t"                # used to be "sudo emacs -nw"
     #alias emacs="emacsclient -c -a emacs"           # new - opens the GUI with alternate non-daemon
     alias sc-cat='systemctl cat'
@@ -168,25 +182,26 @@ init-simple-aliases() {
     alias mail=mutt
     alias restore=recover
     alias o=xdg-open
-    alias jl='sudo journalctl -b 0'
-    hash -d scu="$HOME/.config/systemd/user"
-    hash -d scd='/etc/systemd/system/'
-
-    user_commands=(
-        list-units status list-unit-files list-jobs
-        start stop reload restart enable disable)
-
-    for c in $user_commands; do; alias sc-user-$c="systemctl --user $c"; done
-
-
+    alias jl='sudo journalctl -b 0 --no-pager | tail'
+    alias myip='curl ifconfig.co'
+    alias rs='rsync --progress -r'
+    alias simple-server='python3 -m http.server'
     alias drm='docker rm'
     alias di='docker inspect'
     alias dps='docker ps'
+    # Long task: C-z fg && beep
     alias ding=bell
+    alias beep=bell
     alias r=reload
     alias fix-null='sudo /bin/sh -c "rm -f /dev/null; mknod -m 666 /dev/null c 1 3"'
     # Move to last made photos
     alias cd-last-photos="/media/photos/Photos/Everyday/*(oc[1,1])"
+    alias sc-status-vpn="sc-status openvpn@\*"
+    alias sc-stop-vpn="sc-stop $(systemctl show openvpn@\* --state active -p Id --value)"
+    # Start docker with openvpn running
+    alias music="urxvt -name urxvt.ncmpcpp -e ncmpcpp"
+
+
 
 
     # OS-depend aliases
@@ -217,7 +232,7 @@ init-complex-aliases() {
     }
 
     ssh() {
-        ssh-add -l >/dev/null || ssh-add
+        ssh-add -l >/dev/null || ssh-add -t 2h
         /usr/bin/ssh "$@"
     }
 
@@ -242,6 +257,14 @@ init-complex-aliases() {
         mv $1 /tmp/
     }
 
+    # delete file, but save copy in /tmp
+    wait4net() {
+        echo "Waiting for internet (ping every sec)..."
+        while ! ping 8.8.8.8 -c 1 >/dev/null 2>&1; do sleep 1; done
+        echo "Internet at $(date)!"
+        ding "Internet!"
+    }
+
     # Make directory and cd into that
     mkcd() {
         mkdir -p "$@" && eval cd "\"\$$#\"";
@@ -254,19 +277,42 @@ init-complex-aliases() {
 
     # PLAY bell sound (at the end of long commands)
     bell() {
-        (notify-send "Command complete $1" &
-            aplay ~/Dropbox/confiles/linux/bin/ding.wav 2>/dev/null &)
+        (notify-send "${1:-Command complete}"
+         aplay ~/Dropbox/confiles/linux/sounds/ding.wav 2>/dev/null &)
     }
 
-    bakup () {
-        cp "$1" "$1.bak" && echo "Made backup $1.bak"
+    backup () {
+        PREFIX=""
+        if ! [[ -w $(dirname "$1") ]] ; then PREFIX="sudo" fi
+        $PREFIX cp "$1" "$1.bak" && echo "Made backup $1.bak"
     }
 
     bak () {
-        mv "$1" "$1.bak" && echo "$1 -> $1.bak"
+        PREFIX=""
+        if ! [[ -w $(dirname "$1") ]] ; then PREFIX="sudo" fi
+        $PREFIX mv "$1" "$1.bak" && echo "$1 -> $1.bak"
     }
     unbak () {
-        mv "$1.bak" "$1" && echo "$1.bak -> $1"
+        PREFIX=""
+        if ! [[ -w $(dirname "$1.bak") ]] ; then PREFIX="sudo" fi
+        $PREFIX mv "$1.bak" "$1" && echo "$1.bak -> $1"
+    }
+    saferm () {
+        mv "$1" /media/hdd-backup/Trash
+    }
+
+    sms () {
+        m start -a android.intent.action.VIEW -d sms:$1 --es sms_body "Hello" --ez exit_on_sent true
+    }
+
+    my-find() {
+        if [[ $# == 1 ]] ; then
+            CMD="find . -iname \"*$1*\""
+        else
+            CMD="find $1 -iname \"*$2*\" $3"
+        fi
+        echo $CMD
+        eval $CMD
     }
 
     # fe [FUZZY PATTERN] - Open the selected file with the default editor
@@ -291,7 +337,19 @@ init-complex-aliases() {
         fi
     }
 
+    docker-start() {
+        SRV=$(systemctl show "openvpn@*" --state active -p Id --value)
+        sc-stop $SRV && sc-start docker && sc-start $SRV && echo Service $SRV active again
+    }
 
+
+    # Shows who is listening port $1 with process info
+    who-listen() {
+        exec 3<&1 # new pipe to show output of nestat in stdout
+        # Netstat and then ps -p of process that netstat showed to us
+        sudo netstat -tulpn | grep :$1 >&3 3>&- | grep -P -o '\d+(?=/)' | sort -u | xargs -r ps -up
+        exec 3>&- # close pipe
+    }
 
     # # fd - cd to selected directory
     # fd() {
@@ -312,6 +370,8 @@ init-complex-aliases() {
         local dir
         file=$(fzf +m -q "$1") && dir=$(dirname "$file") && cd "$dir"
     }
+
+    dbash() { docker exec -it $1 bash }
 
     fag() {
     ag --hidden --nobreak --nonumbers --noheading --depth 5 . | fzf
@@ -336,11 +396,28 @@ init-complex-aliases() {
         fi
     }
 
+    # Downlaods a video from youtube to android
+    andr-vid() {
+        mkcd ~/Android/Videos/${2:-/}
+        youtube-dl "$1" -f 'bestvideo[width<=1280]+bestaudio/best[width<=1280]'  --write-sub  --write-description
+        ding "video downloaded"
+    }
+
     fzf-locate() { locate "*" | fzf -e }
     fzf-playonlinux() { playonlinux --run '$(ls ~/.PlayOnLinux/shortcuts | fzf -e)' ;}
+
+    # clock out from emacs if script exists
+    _emacs-clock-out() {
+        =emacs-clock-out 2>/dev/null && emacs-clock-out
+    }
 }
 
 init-bindkeys() {
+    # Transponse two command arguments before cursor.
+    toggle-vim() {
+        bindkey -v
+    }
+
     # Transponse two command arguments before cursor.
     widget-transponse-args() {
         # z flag is for split string as shell parsing to find words
@@ -360,6 +437,9 @@ init-bindkeys() {
     bindkey '\C-i' complete-word
     bindkey '\e#' pound-insert
 
+    zle -N toggle-vim
+    bindkey '\C-z' toggle-vim
+
     # autoload -U -- ~/dotfiles/.zshfunc/[^_]*(:t)
 
     # Ctrl-X, U - and you can enter any name of widget to execute
@@ -372,9 +452,10 @@ init-bindkeys() {
     zle -N insert-sudo insert_sudo
     bindkey "^[s" insert-sudo
 
-    function dir-up { cd ..; zle reset-prompt }
-    zle -N dir-up
-    bindkey "^h" dir-up
+    # When I edit path I often press C-h for deleting part of it like in helm
+    # function dir-up { cd ..; zle reset-prompt }
+    # zle -N dir-up
+    # bindkey "^h" dir-up
 
 
     function dir-back { cd -1; zle reset-prompt }
@@ -383,7 +464,7 @@ init-bindkeys() {
     bindkey "^L" clear-screen
 
     # Auto ls on RET
-    my-lsret() { [[ -z $BUFFER ]] && BUFFER='ls'; zle accept-line }
+    my-lsret() { [[ -z $BUFFER ]] && BUFFER='ls -lth --group-directories-first'; zle accept-line }
     zle -N my-lsret
     bindkey "" my-lsret
 
